config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  
  get '/update_cities/:state_name', to: 'contacts#update_cities'
  get 'search', to: "search#contacts"

  root 'contacts#index'
end

app/models/address.rb
class Address < ApplicationRecord
  # Associations
  belongs_to :contact

  # Validations
	validates :street, :zip_code, :state, :city, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
end

app/models/contact.rb
class Contact < ApplicationRecord	
	# Enums
	enum gender: {:male => 0, :female => 1}

	# Associations
	has_and_belongs_to_many :preferences
	
	has_one :address, dependent: :destroy
	accepts_nested_attributes_for :address

	has_many :phones, dependent: :destroy
	accepts_nested_attributes_for :phones, reject_if: :all_blank, allow_destroy: true

	# paperclip
	has_attached_file :picture, styles: {large: "200x200>", medium: "100x100>", thumb: "50x50>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :picture, content_type: /\Aimage\/.*\z/

	# Validations
	validates :name, :email, :birth_date, :gender, presence: true

	# Scopes
	scope :search, -> (term, page) { where("lower(name) LIKE ?", "%#{term.downcase}%").page(page).per(5)}
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :contact
end

app/models/preference.rb
class Preference < ApplicationRecord
	# Associations
  has_and_belongs_to_many :contacts
end

app/models/state.rb
class State < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all.page(params[:page]).per(10)
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    respond_to do |format|
      format.js
    end
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    @contact.build_address    
  end

  # GET /contacts/1/edit
  def edit
    load_cities_by_state(@contact.address.state)
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to(contacts_path, notice: 'Contato criado com sucesso.') }
        format.json { render :show, status: :created, location: @contact }
      else
        unless @contact.address.state.blank?
          load_cities_by_state(@contact.address.state)
        end

        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to(contacts_path, notice: 'Contato atualizado com sucesso.') }
        format.json { render :show, status: :ok, location: @contact }
      else
        unless @contact.address.state.blank?
          load_cities_by_state(@contact.address.state)
        end

        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contacts = Contact.find(params[:id].split(","))

    @contacts.each do |contact|
      contact.destroy
    end

    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contato removido com sucesso.' }
      format.json { render json: {"msg": "Contato removido com sucesso"} }
    end
  end

  def update_cities
    state = State.find_by(name: params[:state_name])
    @cities = City.where("state_id = ?", state.id)
    
    respond_to  do |format|
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    def load_cities_by_state(state_name)
      state = State.find_by(name: state_name)
      @cities = City.where("state_id = ?", state.id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:picture, :name, :email, :birth_date, :gender, :preference_ids => [],
        :address_attributes =>[:street, :zip_code, :city, :state],
        :phones_attributes => [:id, :number, :_destroy]
      )
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def contacts
    @contacts = Contact.search(params[:q], params[:page])
    render "contacts/index"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def error_tag(model, attribute)
		if model.errors.has_key?(attribute)
			tag.div(tag.span("", :class => 'glyphicon glyphicon-remove', :'aria-hidden' => "true"))
		end
	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
	OptionsForGenders = Struct.new(:id, :description)

	def options_for_genders
		Contact.genders_i18n.map do |key, value|
			OptionsForGenders.new(key, value)
		end	
	end

end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/contacts/_form.html.erb
<% if contact.errors.any? %>
  <div id="error_explanation">
    <h2><%= t('general.form_error') %> </h2>

    <ul>
    <% contact.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: contact, local: true, html: {multipart: true}) do |f| %>
  
  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :picture %>
      <%= image_tag(contact.picture.url(:medium), id: "previewImg") %>
      <%= f.file_field :picture, id: "pictureId", class: "btn" %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :name %>
      <%= f.text_field :name, id: :contact_name, class: "form-control" %>
      <%= error_tag(contact, :name) %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-sm-4">
      <%= f.label :email %>
      <%= f.text_field :email, id: :contact_email, class: "form-control" %>
      <%= error_tag(contact, :email) %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-sm-3">
      <%= f.label :birth_date %>
      <%= f.text_field(:birth_date, id: :contact_birth_date, value: "#{l(contact.birth_date) unless contact.birth_date.blank? }", class: "datepicker form-control") %>
      <%= error_tag(contact, :birth_date) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label(:gender) %>
    <%= f.collection_radio_buttons(:gender, options_for_genders, :id, :description) do |b|%>
      <div class="radio-inline">
        <%= b.label { b.radio_button + b.text } %>
      </div>
    <% end%>
    <%= error_tag(contact, :gender) %>
  </div>

  <h3><%= Address.model_name.human %></h3>
  <%= f.fields(model: :address) do |address| %>

    <div class="row">
      <div class="form-group col-sm-3">
        <%= address.label(:street) %>
        <%= address.text_field(:street, class: "form-control") %>
        <%= error_tag(contact.address, :street) %>
      </div>
    
      <div class="form-group col-sm-3">
        <%= address.label(:zip_code) %>
        <%= address.text_field(:zip_code, class: "form-control", id: "cep") %>
        <%= error_tag(contact.address, :zip_code) %>
      </div>
    </div>

    <div class="row">
      <div class="form-group col-sm-3">
        <%= address.label(:state) %>
        <%= address.collection_select(:state, State.all, :name, :name, {prompt: true, selected: contact.address.state}, {class: "form-control", id: "states_select"}) %>
        <%= error_tag(contact.address, :state) %>
      </div>

      <div class="form-group col-sm-3">
        <%= address.label(:city) %>
        <% if contact.address.state.blank? %>
          <%= address.collection_select(:city, City.all, :name, :name, {prompt: true, selected: contact.address.city}, {class: "form-control", id: "cities_select", disabled: true}) %>
          <%= error_tag(contact.address, :city) %>
        <% else %>
          <%= address.collection_select(:city, @cities, :name, :name, {prompt: true, selected: contact.address.city}, {class: "form-control", id: "cities_select"}) %>
        <% end %>
      </div>
    
    </div>
  <% end %>

  
  <div id="phones">    
    <h3><%= Phone.model_name.human(count: 2) %></h3>
    <%= link_to_add_association('[Adicionar Telefone]', f, :phones) %>
    
    <%= f.fields(model: :phones) do |phone| %>
      <%= render(partial: 'phone_fields', locals: {f: phone}) %>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label(:preferences) %>
    <%= f.collection_check_boxes(:preference_ids, Preference.all, :id, :name) do |b|%>
      <div class="checkbox-inline">
        <%= b.label { b.check_box + b.text } %>
      </div>
    <% end %>
  </div>

  <div class="actions">
    <%= f.button(t('buttons.save'), class: "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Salvando..."}) %>
  </div>
<% end %>

<script>
  
$(function(){
  
  $("#states_select").on("change", function(){
    $.ajax({
         url: '/update_cities/' + $('#states_select option:selected').val(),
         type: 'GET',
         success: function(resp) {
            console.log("Dynamic city select ok!");
         },
         error: function( req, status, err ) {
           console.log("Error: " + status);
         }
    });
  });

  $("#pictureId").on("change", function(event) {
    var $previewImg = $("#previewImg");

    var files = event.target.files;
    var image = files[0]
    var reader = new FileReader();
    reader.onload = function(file) {
      var image_base64 = file.target.result;
      $previewImg.attr("src", image_base64);
      $previewImg.css("maxWidth", "100px");
      $previewImg.css("maxHeight", "100px");
    }
    reader.readAsDataURL(image);
  });

});

</script>

app/views/contacts/_phone_fields.html.erb
<div class="nested-fields">
	<div class="row">
		<div class="form-group col-sm-3">
  		<%= f.label(:number) %>
  		<%= f.text_field(:number, class: "form-control phone-number") %>
  		<%= link_to_remove_association('remover', f) %>
		</div>
	</div>
</div>

app/views/contacts/_show.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">

    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title" id="myModalLabel"><%= @contact.name %></h4>
    </div>

    <div class="modal-body">

      <%= image_tag(@contact.picture.url(:medium)) %>

      <p>
        <strong><%= Contact.human_attribute_name('email') %>:</strong>
        <%= @contact.email %>
      </p>

      <p>
        <strong><%= Contact.human_attribute_name('birth_date') %>:</strong>
        <%= @contact.birth_date.strftime('%d/%m/%Y') %>
      </p>

      <p>
        <strong><%= Contact.human_attribute_name('gender') %>:</strong>
        <%= @contact.gender_i18n %>
      </p>

      <p>
        <strong><%= Address.human_attribute_name('zip_code') %>:</strong>
        <%= @contact.address.zip_code %>
      </p>

      <p>
        <strong><%= Address.human_attribute_name('street') %>:</strong>
        <%= @contact.address.street %>
      </p>

      <p>
        <strong><%= Address.human_attribute_name('city') %>:</strong>
        <%= @contact.address.city %>
      </p>

      <p>
        <strong><%= Address.human_attribute_name('state') %>:</strong>
        <%= @contact.address.state %>
      </p>

      <p>
        <strong><%= Contact.human_attribute_name('preferences') %>:</strong>
        
        <% if @contact.preferences.empty? %>
          Nenhuma prefência
        <% else %>

          <% @contact.preferences.each do |p| %>
            <%= "#{p.name} | " %>
          <%end%>

        <% end %>
      </p>

    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Fechar</button>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<h1><%= t('messages.editing', model: @contact.model_name.human) %></h1>

<%= render(partial: 'form', locals: {contact: @contact}) %>

<%= link_to(t('buttons.show'), @contact) %> |
<%= link_to(t('buttons.back'), contacts_path) %>

app/views/contacts/index.html.erb
<h1><%= @contacts.model_name.human(count: 2) %></h1>

<table class="table table-condensed">
  <thead>
    <tr>
      <th><input type="checkbox" class="checkAll" name="checkAll" /></th>
      <th><%= @contacts.human_attribute_name('name') %></th>
      <th><%= @contacts.human_attribute_name('email') %></th>
      <th><%= @contacts.human_attribute_name('birth_date') %></th>
      <th><%= @contacts.human_attribute_name('gender') %></th>
      <th><a id="deletar-contatos" class="btn btn-danger btn-sm btn-circle" href="#" role="button"><i class="fa fa-times fa-lg" aria-hidden="true"></i></a></th>
      <!--<th colspan="3"></th>-->
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= check_box_tag(contact.name, contact.id) %></td>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= l(contact.birth_date) %></td>
        <td><%= contact.gender_i18n %></td>
        <td>
          <%= link_to(contact, class: "btn btn-info btn-sm btn-circle", remote: true, data: { toggle: "modal", target: "#modal-window"}) do %>
            <i class="fa fa-search fa-lg" aria-hidden="true"></i>
          <% end %>
        
          <%= link_to(edit_contact_path(contact), class: "btn btn-success btn-sm btn-circle") do %>
            <i class="fa fa-pencil fa-lg" aria-hidden="true"></i>
          <% end %>        
        
          <%= link_to(contact, method: :delete, data: { confirm: 'Deletar contato?' }, class: "btn btn-danger btn-sm btn-circle") do %>
            <i class="fa fa-times fa-lg" aria-hidden="true"></i>
          <% end%>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="row">
    <div class="text-center">
        <%= paginate(@contacts) %>
    </div>
</div>

<br>

<%= link_to(new_contact_path, class: "btn btn-default") do %>
  <strong><%=t('buttons.new')%></strong>
<% end %>

<div id="modal-window" class="modal fade" role="dialog" aria-labelledby="myModalLabel">
</div>

app/views/contacts/new.html.erb
<h1> <%= t('messages.new', model: @contact.model_name.human) %> </h1>

<%= render(partial:'form', locals: {contact: @contact}) %>

<%= link_to(t('buttons.back'), contacts_path) %>

app/views/contacts/show.js.erb
$("#modal-window").html('<%= escape_javascript(render partial:"contacts/show") %>');
$("#modal-window").modal('show');

app/views/contacts/update_cities.js.erb
$("#cities_select").empty();
$("#cities_select").attr('disabled', false);

<% @cities.each do |c| %>
	$("#cities_select").append("<option value='<%=c.name%>'><%= c.name %></option>");
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    
    <div class="container">

      <div class="row">
        <div class="text-center">
          <%= form_tag(search_path, method: :get) do %>
            <%= text_field_tag(:q, params[:q], {placeholder: "Pesquisar contato..."}) %>
            <%= submit_tag("Pesquisar", class: "btn btn-default") %>
          <%end%>
        </div>
      </div>

      <%= yield %>
    </div>

    <% if notice %>
      <%= javascript_tag "$.notify( { message: '#{notice}'},
                                    { type: 'success', 
                                      placement: { 
                                        from: 'top',
                                          align: 'center'
                                      }
                                     }
                                   );" %>
    <%end%>

    <%if alert %>
        <%= javascript_tag "$.notify( { message: '#{notice}'},
                                      { type: 'danger', 
                                        placement: { 
                                          from: 'top',
                                            align: 'center'
                                        }
                                       }
                                     );" %>
    <%end%>

  </body>
   
</html>

app/views/search/contacts.html.erb
<h1>Search#contacts</h1>
<p>Find me in app/views/search/contacts.html.erb</p>